### ISSUE TITLE
What about the other countries?

### ISSUE THREAD

**Issue by santomet** [santomet/sktv-forwarders#4]
Guys, I want a small discussion about the other countries. My aim is to maintain only Slovak and Czech channels as far as it gets.

About other countries, some links work and some don't. Do we want to keep the support there? Is it used in some IPTV list?

**Comment by NexusSfan** [comment]
For other countries, there is mostly already IPTV channels for them. If there is a IPTV channel from another country which has Geoblocking but works in Czech/Slovak countries, then maybe you could add it.

**Comment by santomet** [comment]
Well I prefer to keep only Czech and Slovak on my part. I will go through all other channels and remove the broken ones. (I will only comment out the code to keep the record about how these were used)
