### ISSUE TITLE
Add back m3u8 Referer code

### ISSUE THREAD

**Issue by NexusSfan** [santomet/sktv-forwarders#5]
For Nova channels, the referer on the new site shows VLC method, and no m3u8 method (m3u8 is used a lot with IPTV). I think you should add back the m3u8 instructions.

**Comment by santomet** [comment]
Did that actually work? Maybe I tested it in a wrong way. I might also forge a m3u8 playlist with these straight away 🤔

**Comment by santomet** [comment]
So it actually does not work properly. Markiza/Nova need the referer also for the chunks and VLC does not use the referer to those. I have also tried to add adaptive-use-access option to #EXTVLCOPT, however, this is the result:

`main input error: unsafe option "adaptive-use-access" has been ignored for security reasons`

Is there any other player I should try that supports #EXTVLCOPT tags?

But I will do two things:

- Add proper information about all this
- forge an m3u8 where #EXTVLCOPT tags are already present

**Comment by NexusSfan** [comment]
Commit 4935ed0 seems to add the Referer to the m3u8, and should work with clients such as Kodi and Hypnotix. I have yet to try it with Hypnotix though.

**Comment by santomet** [comment]
Yes that is the problem, there is no universal way to do this. Both Kodi and mpv have open issues about supporting the VLC m3u extensions or creating their own extensions. I will close this for now.

**Comment by santomet** [comment]
My bad, in latest version of VLC, including the #EXTVLCOPT works nicely. So if you use VLC, just providing link to the forwarder is enough.
